apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test1-api
  namespace: test1
subjects:
- kind: ServiceAccount
  name: test1-api
roleRef:
  kind: Role
  name: test1-api
  apiGroup: rbac.authorization.k8s.io
